export const LOAD_RECIPES_SUCCESS = 'LOAD_RECIPES_SUCCESS';
export const ADD_EDIT_RECIPES_BTN_SUCCESS = 'ADD_EDIT_RECIPES_BTN_SUCCESS';
export const ADD_RECIPE__SUCCESS = 'ADD_RECIPE__SUCCESS';
export const EDIT_RECIPE__SUCCESS = 'EDIT_RECIPE__SUCCESS';
export const DELETED_ITEM_SUCCESS = 'DELETED_ITEM_SUCCESS';